### ISSUE TITLE
SIM card, or plan for SIM card

### ISSUE THREAD

**Issue by Aariq** [BrunaLab/research_trip_checklists#1]
Having a working smartphone is super useful when you're in a foreign country.  You can pick up cheap SIM cards upon arrival at most airports, I think, or you might be able to get one near wherever you're staying. Having a plan for how you're going to get your phone working before you depart is essential, IMO.  Maybe this matters less if you're somewhere with generally poor cell service or abundant free public wifi.

**Comment by embruna** [comment]
Oh of course...not sure how this slipped by. We had "phone" on the list, but i will add a note to purchase local sim card
